"""add business_contexts table

Revision ID: 1d2dc1fc2e4b
Revises: 129e21e2fed1
Create Date: 2026-09-21 00:04:44.471788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2dc1fc2e4b'
down_revision: Union[str, None] = '129e21e2fed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_contexts',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('monitored_domains', sa.JSON(), nullable=False),
    sa.Column('notification_level', sa.String(length=20), nullable=False),
    sa.Column('stated_objectives', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_contexts_company_id'), ['company_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_contexts_company_id'))

    op.drop_table('business_contexts')
    # ### end Alembic commands ###
