"""task human-in-the-loop fields and statuses

Revision ID: 4166e4786c10
Revises: 52b77617cfa9
Create Date: 2026-09-20 18:09:59.422938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4166e4786c10'
down_revision: Union[str, None] = '52b77617cfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Autogenerate does not reliably diff Enum member changes (especially on
# SQLite, where an Enum is just a CHECK constraint), so the status column's
# constraint is widened here by hand. Values are inlined rather than imported
# from app.core.entities.task so this migration keeps meaning exactly what it
# meant at the time it was written, regardless of later model changes.
_OLD_STATUS_VALUES = ("pending_validation", "open", "in_progress", "done", "cancelled")
_NEW_STATUS_VALUES = (*_OLD_STATUS_VALUES, "rejected", "executed")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(*_OLD_STATUS_VALUES, name='taskstatus'),
            type_=sa.Enum(*_NEW_STATUS_VALUES, name='taskstatus'),
            existing_nullable=False,
        )
        batch_op.add_column(sa.Column('pending_action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('correlation_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_pending_action'), ['pending_action'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_pending_action'))
        batch_op.drop_index(batch_op.f('ix_tasks_correlation_id'))
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('pending_action')
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(*_NEW_STATUS_VALUES, name='taskstatus'),
            type_=sa.Enum(*_OLD_STATUS_VALUES, name='taskstatus'),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
