"""initial data core schema

Revision ID: 52b77617cfa9
Revises: 
Create Date: 2026-09-20 14:25:16.852488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b77617cfa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_related_entity_type'), ['related_entity_type'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('communications',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='communicationdirection'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communications_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_related_entity_type'), ['related_entity_type'], unique=False)

    op.create_table('customers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_company_id'), ['company_id'], unique=False)

    op.create_table('documents',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_related_entity_type'), ['related_entity_type'], unique=False)

    op.create_table('opportunities',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'PURSUED', 'DISMISSED', name='opportunitystatus'), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_related_entity_type'), ['related_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)

    op.create_table('risks',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='riskstatus'), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_related_entity_type'), ['related_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risks_status'), ['status'], unique=False)

    op.create_table('suppliers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_company_id'), ['company_id'], unique=False)

    op.create_table('tasks',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VALIDATION', 'OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.Enum('COMPANY', 'SUPPLIER', 'CUSTOMER', 'PRODUCT', 'TRANSACTION', name='relatedentitytype'), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_related_entity_id'), ['related_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_related_entity_type'), ['related_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_source_event_id'), ['source_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('transactions',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PURCHASE_ORDER', 'INVOICE', 'SALES_ORDER', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PAID', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_company_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_company_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_company_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risks_status'))
        batch_op.drop_index(batch_op.f('ix_risks_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_risks_severity'))
        batch_op.drop_index(batch_op.f('ix_risks_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_risks_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_risks_company_id'))

    op.drop_table('risks')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_opportunities_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_company_id'))

    op.drop_table('opportunities')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_documents_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_company_id'))

    op.drop_table('customers')
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communications_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_communications_related_entity_id'))
        batch_op.drop_index(batch_op.f('ix_communications_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_communications_company_id'))

    op.drop_table('communications')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_events_correlation_id'))

    op.drop_table('events')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_related_entity_type'))
        batch_op.drop_index(batch_op.f('ix_contacts_related_entity_id'))

    op.drop_table('contacts')
    op.drop_table('companies')
    # ### end Alembic commands ###
