"""add contact company_id and communication/document provenance fields

Revision ID: 6baa8061c9ed
Revises: adec626d276c
Create Date: 2026-09-21 20:41:17.985749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baa8061c9ed'
down_revision: Union[str, None] = 'adec626d276c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_communications_source'), ['source'], unique=False)
        batch_op.create_index('ix_communications_source_external_id', ['source', 'external_id'], unique=True)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Uuid(), nullable=False))
        batch_op.create_index(batch_op.f('ix_contacts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_foreign_key('fk_contacts_company_id_companies', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_source'), ['source'], unique=False)
        batch_op.create_index('ix_documents_source_external_id', ['source', 'external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_source_external_id')
        batch_op.drop_index(batch_op.f('ix_documents_source'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_company_id_companies', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_id'))
        batch_op.drop_column('company_id')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index('ix_communications_source_external_id')
        batch_op.drop_index(batch_op.f('ix_communications_source'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
