"""add task domain

Revision ID: 8073a82d9f49
Revises: 4ba6953c0de3
Create Date: 2026-09-22 23:42:47.466322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8073a82d9f49'
down_revision: Union[str, None] = '4ba6953c0de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_domain'), ['domain'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_domain'))
        batch_op.drop_column('domain')

    # ### end Alembic commands ###
