"""expand business_context configuration fields

Revision ID: adec626d276c
Revises: 1d2dc1fc2e4b
Create Date: 2026-09-21 00:48:34.564102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adec626d276c'
down_revision: Union[str, None] = '1d2dc1fc2e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_model', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('home_focus', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('declared_baselines', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('learned_notes', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_contexts', schema=None) as batch_op:
        batch_op.drop_column('learned_notes')
        batch_op.drop_column('declared_baselines')
        batch_op.drop_column('home_focus')
        batch_op.drop_column('business_model')
        batch_op.drop_column('country')
        batch_op.drop_column('company_size')

    # ### end Alembic commands ###
